steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'my-service'
  - '--image'
  - 'gcr.io/trainingmodule-285008/tictac-image'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=./kubeconfig.yaml
  - --location=us-central1-c
  - --cluster=cluster1
